# Generated by Django 4.1 on 2023-12-25 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CSVFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='csv_files/')),
            ],
        ),
        migrations.AlterField(
            model_name='amenity',
            name='special_occasion',
            field=models.CharField(blank=True, choices=[('VIP 4 ME', '4ME'), ('Presidential', 'Presidential'), ('VIP 3 ME', '3ME'), ('Small fruit', 'Small fruit')], max_length=300, null=True),
        ),
    ]
