# Generated by Django 4.1 on 2023-12-25 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0002_csvfile_alter_amenity_special_occasion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenities_CSV',
            fields=[
                ('big_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('day_of_week', models.CharField(max_length=200)),
                ('amenity_code', models.CharField(max_length=150)),
                ('iventory', models.IntegerField(default=0)),
                ('reserved', models.IntegerField(default=0, null=True)),
                ('date_of_input', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='amenity',
            name='special_occasion',
            field=models.CharField(blank=True, choices=[('VIP 4 ME', '4ME'), ('Small fruit', 'Small fruit'), ('VIP 3 ME', '3ME'), ('Presidential', 'Presidential')], max_length=300, null=True),
        ),
    ]
