# Generated by Django 4.1 on 2024-02-10 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0009_spacial_amenities_alter_amenity_special_occasion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Replenishment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amenity_replen', models.CharField(max_length=300)),
                ('amount_day', models.IntegerField(blank=True, default=0)),
                ('date_of_input', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='amenity',
            name='special_occasion',
            field=models.CharField(blank=True, choices=[('VIP3ME', 'VIP3ME'), ('VIP2', 'VIP2'), ('VIP1', 'VIP1'), ('VIP6', 'VIP6'), ('Presidential', 'Presidential'), ('VIP4', 'VIP4'), ('VIP5', 'VIP5'), ('None', 'None'), ('VIP5ME', 'VIP5ME'), ('VIP3', 'VIP3'), ('VIP4ME', 'VIP4ME')], max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='spacial_amenities',
            name='amenity_code',
            field=models.CharField(blank=True, choices=[('VIP3ME', 'VIP3ME'), ('VIP2', 'VIP2'), ('VIP1', 'VIP1'), ('VIP6', 'VIP6'), ('Presidential', 'Presidential'), ('VIP4', 'VIP4'), ('VIP5', 'VIP5'), ('None', 'None'), ('VIP5ME', 'VIP5ME'), ('VIP3', 'VIP3'), ('VIP4ME', 'VIP4ME')], max_length=150),
        ),
        migrations.AlterField(
            model_name='spacial_amenities',
            name='amenity_type',
            field=models.CharField(blank=True, choices=[('Aniversary cake', 'Aniversary cake'), ('Birthady cake', 'Birthady cake'), ('Sliced fruit platter', 'Sliced fruit platter'), ('Canapes', 'Canapes'), ('Celebration cake', 'Celebration cake'), ('8" cake', '8" cake'), ('Honeymoon cake', 'Honeymoon cake'), ('6" cake', '6" cake'), ('Special amenities', 'Special amenities')], max_length=250),
        ),
        migrations.AlterField(
            model_name='spacial_amenities',
            name='day_of_week',
            field=models.CharField(blank=True, choices=[('Tuesday', 'Tuesday'), ('Saturday', 'Saturday'), ('Wednesday', 'Wednesday'), ('Friday', 'Friday'), ('Thursday', 'Thursday'), ('Sunday', 'Sunday'), ('Monday', 'Monday')], max_length=200),
        ),
    ]
